package Forms;

import Funciones.Datos;
import Funciones.Operaciones;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 * @author ROQUEARMANDORAMIREZP
 */
public class FrmCarpetear extends javax.swing.JInternalFrame {

    int IntFila;
    Datos DAT;
    Operaciones Operacion = new Operaciones();
    String[][] MatrixCodNom;

    DefaultTableModel modelo = new DefaultTableModel();

    public FrmCarpetear() {
        this.DAT = new Datos();
        initComponents();
        if (DAT.MatrixNOEsNula()) {
            CargarDatos();//carga datos solo si hay datos
        }
        ComboPerfil.setSelectedIndex(-1); //no selecciona nada

        modelo.addColumn("Correo Destino");
        modelo.addColumn("Codigo Perfil");
        modelo.addColumn("Cargo");
        modelo.addColumn("CV");
        modelo.addColumn("Asunto");
        modelo.addColumn("Empresa");
        modelo.addColumn("Empleador");
        modelo.addColumn("Mensaje");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        ComboPerfil = new javax.swing.JComboBox<>();
        CmdAgregar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        TxtCargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtCV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtAsunto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtLabia = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtEmpresa = new javax.swing.JTextField();
        TxtEmpleador = new javax.swing.JTextField();
        CmdBorraCv = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Grdbuscar = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        CmdCancelar = new javax.swing.JButton();
        CmdEnviar = new javax.swing.JButton();
        CmdBorrar = new javax.swing.JButton();

        setMaximizable(true);
        setTitle("Carpetear");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/package_go.png"))); // NOI18N

        jLabel1.setText("Correo de Destino:");

        jLabel2.setText("Perfil a Usar:");

        TxtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtCorreoMouseClicked(evt);
            }
        });
        TxtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCorreoKeyTyped(evt);
            }
        });

        CmdAgregar.setText("Agregar");
        CmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdAgregarActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcional:"));
        jLayeredPane1.setName("Opcional"); // NOI18N

        jLabel4.setText("Cargo:");

        TxtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtCargoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCargoKeyTyped(evt);
            }
        });

        jLabel3.setText("CV:");

        TxtCV.setEditable(false);
        TxtCV.setBackground(new java.awt.Color(255, 255, 255));
        TxtCV.setToolTipText("Haga Doble Click para Seleccionar Cv");
        TxtCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtCVMouseClicked(evt);
            }
        });

        jLabel5.setText("Asunto:");

        TxtAsunto.setToolTipText("");
        TxtAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtAsuntoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAsuntoKeyTyped(evt);
            }
        });

        jLabel6.setText("Mensaje:");

        TxtLabia.setColumns(20);
        TxtLabia.setRows(5);
        TxtLabia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtLabiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtLabiaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TxtLabia);

        jLabel8.setText("Empleador:");

        jLabel9.setText("Empresa:");

        TxtEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmpresaKeyTyped(evt);
            }
        });

        TxtEmpleador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtEmpleadorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEmpleadorKeyTyped(evt);
            }
        });

        CmdBorraCv.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        CmdBorraCv.setForeground(new java.awt.Color(0, 0, 0));
        CmdBorraCv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/cross_delete_exit_remove_icon.png"))); // NOI18N
        CmdBorraCv.setToolTipText("Borrar Cv Actual");
        CmdBorraCv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdBorraCvActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtCargo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtCV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtAsunto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(TxtEmpleador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(CmdBorraCv, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCargo)
                            .addComponent(TxtAsunto)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(TxtCV, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CmdBorraCv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(50, 50, 50)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtEmpleador, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(TxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmdBorraCv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TxtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtEmpleador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Esquema:"));
        jLayeredPane2.setName("Opcional"); // NOI18N

        Grdbuscar= new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        Grdbuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Grdbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Grdbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrdbuscarMouseClicked(evt);
            }
        });
        Grdbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GrdbuscarKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Grdbuscar);

        jLabel7.setText("Para Eliminar una fila, seleccionela y oprima Supr");

        jLayeredPane2.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 197, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        CmdCancelar.setText("Cancelar");
        CmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCancelarActionPerformed(evt);
            }
        });

        CmdEnviar.setText("Enviar");
        CmdEnviar.setEnabled(false);
        CmdEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdEnviarActionPerformed(evt);
            }
        });

        CmdBorrar.setText("Borrar");
        CmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboPerfil, 0, 563, Short.MAX_VALUE)
                            .addComponent(TxtCorreo))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CmdAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CmdBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1)
                            .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CmdEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmdCancelar)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CmdAgregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CmdBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdCancelar)
                    .addComponent(CmdEnviar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrdbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrdbuscarMouseClicked
        IntFila = (Grdbuscar.rowAtPoint(evt.getPoint())); //obtiene el numero de fila de la tabla.
        //IntCodFila = Integer.parseInt(String.valueOf(Grdbuscar.getValueAt(IntFila, 0))); //obtiene el Valor del COD seleccionada. si no hago esas conversiones redundantes, no funciona...no sé x q

        if (evt.getClickCount() == 2) { //si se hace doble click...
            BorrarFila();
        }
    }//GEN-LAST:event_GrdbuscarMouseClicked

    private void CmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCancelarActionPerformed
        this.dispose();    //cierra esta ventana 
    }//GEN-LAST:event_CmdCancelarActionPerformed

    private void TxtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoKeyTyped
        if (TxtCorreo.getText().length() >= 255) {
            evt.consume(); // impide que ingresen más de 255 caracteres
        }

    }//GEN-LAST:event_TxtCorreoKeyTyped

    private void TxtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCargoKeyTyped
        if (TxtCargo.getText().length() >= 50) {
            evt.consume(); // impide que ingresen más de 50 caracteres
        }
    }//GEN-LAST:event_TxtCargoKeyTyped

    private void TxtAsuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAsuntoKeyTyped
        if (TxtAsunto.getText().length() >= 100) {
            evt.consume(); // impide que ingresen más de 100 caracteres
        }
    }//GEN-LAST:event_TxtAsuntoKeyTyped

    private void TxtLabiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLabiaKeyTyped
        if (TxtLabia.getText().length() >= 1000) {
            evt.consume(); // impide que ingresen más de 1000 caracteres
        }
    }//GEN-LAST:event_TxtLabiaKeyTyped

    private void TxtEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpresaKeyTyped
        if (TxtEmpresa.getText().length() >= 200) {
            evt.consume(); // impide que ingresen más de 200 caracteres
        }
    }//GEN-LAST:event_TxtEmpresaKeyTyped

    private void TxtCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCVMouseClicked
        if (evt.getClickCount() == 2) { //si se hace doble click...
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "Documentos de Cv", "docx", "doc", "pdf", "odt");
            fileChooser.setFileFilter(filter);
            int valor = fileChooser.showOpenDialog(fileChooser);
            if (valor == JFileChooser.APPROVE_OPTION) {
                String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                TxtCV.setText(ruta);
            }
            /*else {
            TxtCV.setText("");            
            } 
            //para llamar a un msgbox modificado: más info en:
            https://stackoverflow.com/questions/70455843/create-a-custom-dialog-from-a-jpanel
            https://stackoverflow.com/questions/6325921/custom-dialog-java-swing
            JOptionPane.showMessageDialog(null, new CustomDialog(), "Configure Mensaje", JOptionPane.PLAIN_MESSAGE);*/
            if (TxtCV.getText().length() > 0) {
                TxtCV.setBackground(Color.cyan); //pinta solo si modifican
            } else {
                TxtCV.setBackground(Color.white);
            }
        }
    }//GEN-LAST:event_TxtCVMouseClicked

    private void TxtEmpleadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpleadorKeyTyped
        if (TxtEmpleador.getText().length() >= 200) {
            evt.consume(); // impide que ingresen más de 200 caracteres
        }
    }//GEN-LAST:event_TxtEmpleadorKeyTyped

    private void TxtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCorreoKeyReleased
        //colorea si se ingres mal el correo
        if (Operacion.EsCorreo(TxtCorreo.getText())) {
            TxtCorreo.setBackground(Color.WHITE);
        } else {
            TxtCorreo.setBackground(Color.orange);
            /*TxtCorreo.setBackground(Color.getHSBColor(c8,70,90));
            el HSb no es RGB pero no logré conseguir el color que queria*/
        }
    }//GEN-LAST:event_TxtCorreoKeyReleased

    private void TxtCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCargoKeyReleased
        if (TxtCargo.getText().length() > 0) {
            TxtCargo.setBackground(Color.cyan); //pinta solo si modifican
        } else {
            TxtCargo.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtCargoKeyReleased

    private void TxtEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpresaKeyReleased
        if (TxtEmpresa.getText().length() > 0) {
            TxtEmpresa.setBackground(Color.cyan); //pinta solo si modifican
        } else {
            TxtEmpresa.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtEmpresaKeyReleased

    private void TxtEmpleadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEmpleadorKeyReleased
        if (TxtEmpleador.getText().length() > 0) {
            TxtEmpleador.setBackground(Color.cyan); //pinta solo si modifican
        } else {
            TxtEmpleador.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtEmpleadorKeyReleased

    private void TxtAsuntoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAsuntoKeyReleased
        if (TxtAsunto.getText().length() > 0) {
            TxtAsunto.setBackground(Color.cyan); //pinta solo si modifican
        } else {
            TxtAsunto.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtAsuntoKeyReleased

    private void TxtLabiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLabiaKeyReleased
        if (TxtLabia.getText().length() > 0) {
            TxtLabia.setBackground(Color.cyan); //pinta solo si modifican
        } else {
            TxtLabia.setBackground(Color.white);
        }
    }//GEN-LAST:event_TxtLabiaKeyReleased

    private void CmdBorraCvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdBorraCvActionPerformed
        TxtCV.setText("");
        TxtCV.setBackground(Color.white);
    }//GEN-LAST:event_CmdBorraCvActionPerformed

    private void CmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdAgregarActionPerformed
        if (ComboPerfil.getSelectedIndex() >= 0 && Operacion.EsCorreo(TxtCorreo.getText())) {
            String[] ModeloColumn = new String[8];

            ModeloColumn[0] = TxtCorreo.getText();
            //ModeloColumn[1] = ComboPerfil.getItemAt(ComboPerfil.getSelectedIndex()); obtiene texto selecionado del combobox
            ModeloColumn[1] = MatrixCodNom[ComboPerfil.getSelectedIndex()][0];
            ModeloColumn[2] = TxtCargo.getText();
            ModeloColumn[3] = TxtCV.getText();
            ModeloColumn[4] = TxtAsunto.getText();
            ModeloColumn[5] = TxtEmpresa.getText();
            ModeloColumn[6] = TxtEmpleador.getText();
            ModeloColumn[7] = TxtLabia.getText();

            modelo.addRow(ModeloColumn);

            Grdbuscar.setModel(modelo);

            LimpiaCajas();

            IntFila = -1;
            CmdEnviar.setEnabled(true);
        }
    }//GEN-LAST:event_CmdAgregarActionPerformed

    private void GrdbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GrdbuscarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE || evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            BorrarFila();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
            //if (procede != true) {
            IntFila = Grdbuscar.getSelectedRow();
            //}
        }
    }//GEN-LAST:event_GrdbuscarKeyReleased

    private void CmdEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdEnviarActionPerformed
        if (modelo.getRowCount() > 0 && TxtCorreo.getText().length() < 1) {
            int opci = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Empezar a Enviar " + modelo.getRowCount() + " Cv's?", "Atento!", JOptionPane.YES_NO_OPTION);
            if (opci == JOptionPane.YES_OPTION) {
                boolean todoOk = true;
                String[][] MatrixFinal = DAT.EmpaquetarDatos(modelo);

                for (int i = 0; i < MatrixFinal.length; i++) {
                    File archivo = new File(MatrixFinal[i][1]);
                    if (!archivo.exists()) { //si no existe un archivo
                        JOptionPane.showMessageDialog(null, "Verifique el CV adjunto: " + MatrixFinal[i][1] + "\nPara el Email enviado a: " + MatrixFinal[i][0], "Cv Inexistente", JOptionPane.ERROR_MESSAGE);
                        todoOk = false;
                        break;//sale del bucle
                    }
                }

                if (todoOk) {
                    FrmEnviaEmail Marioneta = new FrmEnviaEmail();
                    Marioneta.MatrixFinal = MatrixFinal;//pasa la matriz 
                    FrmPrincipal.Escritorio.add(Marioneta);
                    Marioneta.show();

                    this.dispose();    //cierra esta ventana
                }
            }
        } else { //si hay un dato sin agregar, entonces pide que lo borreo o lo ingrese
            JOptionPane.showMessageDialog(null, "Haga click en Agregar o borre los datos incompletos antes de continuar", "Atención", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CmdEnviarActionPerformed

    private void TxtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCorreoMouseClicked
        if (evt.getClickCount() == 2) { //si se hace doble click...
            TxtCorreo.selectAll();
        }
    }//GEN-LAST:event_TxtCorreoMouseClicked

    private void CmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdBorrarActionPerformed
        LimpiaCajas();
    }//GEN-LAST:event_CmdBorrarActionPerformed

    private void LimpiaCajas() {
        TxtCorreo.setText("");
        TxtCargo.setText("");
        TxtCV.setText("");
        TxtAsunto.setText("");
        TxtEmpresa.setText("");
        TxtEmpleador.setText("");
        TxtLabia.setText("");
        ComboPerfil.setSelectedIndex(-1); //no selecciona nada
        TxtCorreo.setBackground(Color.white);//restaura el color original
        TxtCargo.setBackground(Color.white);
        TxtCV.setBackground(Color.white);
        TxtAsunto.setBackground(Color.white);
        TxtEmpresa.setBackground(Color.white);
        TxtEmpleador.setBackground(Color.white);
        TxtLabia.setBackground(Color.white);
        TxtCorreo.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdAgregar;
    private javax.swing.JButton CmdBorraCv;
    private javax.swing.JButton CmdBorrar;
    private javax.swing.JButton CmdCancelar;
    private javax.swing.JButton CmdEnviar;
    private javax.swing.JComboBox<String> ComboPerfil;
    private javax.swing.JTable Grdbuscar;
    private javax.swing.JTextField TxtAsunto;
    private javax.swing.JTextField TxtCV;
    private javax.swing.JTextField TxtCargo;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtEmpleador;
    private javax.swing.JTextField TxtEmpresa;
    private javax.swing.JTextArea TxtLabia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void CargarDatos() {
        MatrixCodNom = DAT.CreateListCodNom();
        for (int j = 0; j < MatrixCodNom.length; j++) {
            ComboPerfil.addItem(MatrixCodNom[j][1]);
        }
    }

    private void BorrarFila() {
        if (IntFila >= 0) {
            int opci = JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Eliminar Email para " + Grdbuscar.getValueAt(IntFila, 0) + "?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (opci == JOptionPane.YES_OPTION) { //elimina si y solo si el usuario acepta
                try {
                    modelo.removeRow(IntFila);
                    Grdbuscar.setModel(modelo);
                    IntFila = -1;
                    JOptionPane.showMessageDialog(null, "Perfil " + Grdbuscar.getValueAt(IntFila, 1) + " eliminado con exito", "Aviso", JOptionPane.DEFAULT_OPTION);
                } catch (Exception e) {
                    //System.out.println ("El error es: " + e.getMessage());
                }
                if (modelo.getRowCount() < 1) {
                    CmdEnviar.setEnabled(false);
                } else {
                    CmdEnviar.setEnabled(true);
                }
            }
        }
    }

}
