package Forms;

import Funciones.Correo;
import javax.swing.JOptionPane;

/**
 * @author ROQUEARMANDORAMIREZP
 */
public class FrmEnviaEmail extends javax.swing.JInternalFrame {

    String[][] MatrixFinal;

    public FrmEnviaEmail() {
        initComponents();
        CmdCerrar.setVisible(false);
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                carga();
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        LblEstado = new javax.swing.JLabel();
        CmdCerrar = new javax.swing.JButton();

        setTitle("Enviando Cv's...");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/package_go.png"))); // NOI18N
        setVisible(true);

        jProgressBar1.setMinimum(1);
        jProgressBar1.setStringPainted(true);

        jLabel1.setText("Estado:");

        LblEstado.setText(" ");

        CmdCerrar.setText("Cerrar");
        CmdCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(LblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CmdCerrar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmdCerrar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCerrarActionPerformed
        this.dispose();    //cierra esta ventana 
    }//GEN-LAST:event_CmdCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdCerrar;
    public javax.swing.JLabel LblEstado;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

    private void carga() {
        int NCorreos = MatrixFinal.length;
        jProgressBar1.setMaximum(NCorreos);

        Correo MandaCorreo = new Correo();
        String[] Arraydestino = new String[4];//4 x q solo se maneja asunto, correodest, labia y adjunto
        jProgressBar1.setValue(1);
        for (int i = 0; i < NCorreos; i++) {
            String StrError = "";
            jProgressBar1.setValue(i + 1);
            LblEstado.setText("Enviado Correo " + (i + 1) + " de " + NCorreos);
            for (int j = 0; j < MatrixFinal[0].length; j++) {
                Arraydestino[j] = MatrixFinal[i][j];
            }
            StrError = MandaCorreo.EnviaCorreos(Arraydestino);
            if (StrError.length() > 0) {
                JOptionPane.showMessageDialog(null, StrError, "Error:", JOptionPane.ERROR_MESSAGE);
            }
        }
        jProgressBar1.setValue(NCorreos);
        JOptionPane.showMessageDialog(null, "Operación Culminada", "Informe", JOptionPane.INFORMATION_MESSAGE);
        LblEstado.setText("Operación Culminada, Puede Cerrar esta Ventana");
        CmdCerrar.setVisible(true);
    }
}
