package Forms;

import Funciones.Datos;
import Funciones.VariablesdeEntorno;
import Funciones.Operaciones;
//para escoger archivos de cv
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * @author ROQUEARMANDORAMIREZP
 */
public class FrmPerfNue extends javax.swing.JInternalFrame {

    String CodModif; //si está vacio...significa que registrará nuevos

    /**
     * Creates new form FrmPerfNue
     */
    public FrmPerfNue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtAsunto = new javax.swing.JTextField();
        TxtNom = new javax.swing.JTextField();
        TxtCaso = new javax.swing.JTextField();
        TxtCV = new javax.swing.JTextField();
        TxtCargo = new javax.swing.JTextField();
        CmdCancelar = new javax.swing.JButton();
        CmdAceptar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtLabia = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setMaximizable(true);
        setTitle("Nuevo Perfil");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/icon_user.gif"))); // NOI18N

        jLabel1.setText("Nombre del Perfil:");

        jLabel2.setText("Usar en Caso de:");

        jLabel3.setText("CV por Defecto:");

        jLabel4.setText("Cargo por Defecto:");

        jLabel5.setText("Asunto por Defecto:");

        TxtAsunto.setToolTipText("");
        TxtAsunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAsuntoKeyTyped(evt);
            }
        });

        TxtNom.setToolTipText("");
        TxtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtNomKeyTyped(evt);
            }
        });

        TxtCaso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCasoKeyTyped(evt);
            }
        });

        TxtCV.setEditable(false);
        TxtCV.setBackground(new java.awt.Color(153, 204, 255));
        TxtCV.setToolTipText("Haga Doble Click Para Seleccionar su CV");
        TxtCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtCVMouseClicked(evt);
            }
        });

        TxtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCargoKeyTyped(evt);
            }
        });

        CmdCancelar.setText("Cancelar");
        CmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdCancelarActionPerformed(evt);
            }
        });

        CmdAceptar.setText("Aceptar");
        CmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdAceptarActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensaje Por Defecto:"));

        jScrollPane1.setHorizontalScrollBar(null);

        TxtLabia.setColumns(20);
        TxtLabia.setRows(5);
        TxtLabia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtLabiaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(TxtLabia);

        jLabel6.setText("Haga Click en las Etiquetas que Desea Agregar:");

        jButton3.setText("Cargo >>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Día >>");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mes >>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Año >>");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Empleador >>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Empresa >>");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CmdAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CmdCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtCV, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(TxtAsunto))
                        .addGap(202, 202, 202)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmdCancelar)
                    .addComponent(CmdAceptar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdAceptarActionPerformed
        if (TxtNom.getText().length() > 0 && TxtCaso.getText().length() > 0
                && TxtCargo.getText().length() > 0 && TxtCV.getText().length() > 0
                && TxtAsunto.getText().length() > 0 && TxtLabia.getText().length() > 0) {
            // si un txtbox esta vacio cancela la operación
            VariablesdeEntorno Variable = new VariablesdeEntorno();
            String[] Datos = new String[Variable.IntColum];
            Datos MatrizPerfil = new Datos();
            if (CodModif.length() > 0) { //si se va a modificar
                Datos[0] = CodModif;
                Datos[1] = TxtNom.getText();
                Datos[2] = TxtCaso.getText();
                Datos[3] = TxtCargo.getText();
                Datos[4] = TxtCV.getText();
                Datos[5] = TxtAsunto.getText();
                Datos[6] = TxtLabia.getText();

                MatrizPerfil.setModifPerfil(Datos);

                JOptionPane.showMessageDialog(null, "Perfil Modificado con éxito", "Notificación:", JOptionPane.INFORMATION_MESSAGE);
            } else { //si se agrega un nuevo registro...
                Operaciones operacion = new Operaciones();

                if (MatrizPerfil.HayEspacio() == true) { //solo se trabaja si hay espacio
                    Datos[0] = operacion.GeneraCodigo();//genera un codigo
                    Datos[1] = TxtNom.getText();
                    Datos[2] = TxtCaso.getText();
                    Datos[3] = TxtCargo.getText();
                    Datos[4] = TxtCV.getText();
                    Datos[5] = TxtAsunto.getText();
                    Datos[6] = TxtLabia.getText();
                    
                    //System.out.println("\n Tamaño antes: " + MatrizPerfil.getMatrixPerfilesTamano());
                    MatrizPerfil.setNewPerfil(Datos);
                    //System.out.println("\n Tamaño: " + MatrizPerfil.getMatrixPerfilesTamano());
                    //MatrizPerfil.ImprimirPerfiles();

                    JOptionPane.showMessageDialog(null, "Perfil Guardado con éxito", "Notificación:", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            this.dispose();    //cierra esta ventana
        }
    }//GEN-LAST:event_CmdAceptarActionPerformed

    private void TxtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomKeyTyped
        if (TxtNom.getText().length() >= 30) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtNomKeyTyped

    private void TxtCasoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCasoKeyTyped
        if (TxtCaso.getText().length() >= 50) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtCasoKeyTyped

    private void TxtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCargoKeyTyped
        if (TxtCargo.getText().length() >= 50) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtCargoKeyTyped

    private void TxtAsuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAsuntoKeyTyped
        if (TxtAsunto.getText().length() >= 100) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtAsuntoKeyTyped

    private void TxtLabiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLabiaKeyTyped
        if (TxtLabia.getText().length() >= 1000) {
            evt.consume(); // impide que ingresen más de 30 caracteres
        }
    }//GEN-LAST:event_TxtLabiaKeyTyped

    private void TxtCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCVMouseClicked
        if (evt.getClickCount() == 2) { //si se hace doble click...
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "Documentos de Cv", "docx", "doc", "pdf", "odt");
            fileChooser.setFileFilter(filter);
            int valor = fileChooser.showOpenDialog(fileChooser);
            if (valor == JFileChooser.APPROVE_OPTION) {
                String ruta = fileChooser.getSelectedFile().getAbsolutePath();
                TxtCV.setText(ruta);
            }
            /*else {
            TxtCV.setText("");            
            } 
            //para llamar a un msgbox modificado: más info en:
            https://stackoverflow.com/questions/70455843/create-a-custom-dialog-from-a-jpanel
            https://stackoverflow.com/questions/6325921/custom-dialog-java-swing
            JOptionPane.showMessageDialog(null, new CustomDialog(), "Configure Mensaje", JOptionPane.PLAIN_MESSAGE);*/
        }

    }//GEN-LAST:event_TxtCVMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //int posicion=TxtLabia.getCaretPosition();//obtengo la ubicación del cursor
        TxtLabia.insert("<<CARGO>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TxtLabia.insert("<<DÍA>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TxtLabia.insert("<<MES>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        TxtLabia.insert("<<AÑO>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void CmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdCancelarActionPerformed
        this.dispose();    //cierra esta ventana 
    }//GEN-LAST:event_CmdCancelarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TxtLabia.insert("<<EMPLEADOR>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        TxtLabia.insert("<<EMPRESA>>", TxtLabia.getCaretPosition());
        TxtLabia.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdAceptar;
    private javax.swing.JButton CmdCancelar;
    public javax.swing.JTextField TxtAsunto;
    public javax.swing.JTextField TxtCV;
    public javax.swing.JTextField TxtCargo;
    public javax.swing.JTextField TxtCaso;
    public javax.swing.JTextArea TxtLabia;
    public javax.swing.JTextField TxtNom;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
