package Forms;

//import Funciones.Datos;
import Funciones.Operaciones;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author ROQUEARMANDORAMIREZP
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Operaciones operacion = new Operaciones();
    //Datos DAT = new Datos();

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Ico/package_go.png")).getImage());//coloca icono al from
        //this.setLocationRelativeTo(null);//centre el formulario en el centro de la pantalla

        operacion.VerficaArchivoInicio("main.dat");

        //this.setLocationRelativeTo(null);//centre el formulario en el centro de la pantalla
        this.setTitle("Carpetéate");//da nombre a la ventana
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCarpetear = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuEmail = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuPerfiles = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuAyuda = new javax.swing.JMenuItem();
        jMenuAcercad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Menú");

        jMenuCarpetear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuCarpetear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/package_go.png"))); // NOI18N
        jMenuCarpetear.setText("Carpetear");
        jMenuCarpetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCarpetearActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCarpetear);
        jMenu1.add(jSeparator1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Configuración");

        jMenuEmail.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/page_edit.png"))); // NOI18N
        jMenuEmail.setText("Email");
        jMenuEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmailActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuEmail);
        jMenu2.add(jSeparator2);

        jMenuPerfiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuPerfiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ico/icon_user.gif"))); // NOI18N
        jMenuPerfiles.setText("Perfiles");
        jMenuPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPerfilesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPerfiles);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuAyuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAyuda);

        jMenuAcercad.setText("Acerca de...");
        jMenuAcercad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercadActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAcercad);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmailActionPerformed
        FrmUsu muestrate = new FrmUsu();
        Escritorio.add(muestrate);
        muestrate.show();
    }//GEN-LAST:event_jMenuEmailActionPerformed

    private void jMenuCarpetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCarpetearActionPerformed
        if (operacion.GetUsuar().length() < 1) {//si no hay correo saca esto
            JOptionPane.showMessageDialog(null, "Necesita Ingresar sus Credenciales de Gmail", "Primero lo primero...", JOptionPane.ERROR_MESSAGE);
            FrmUsu muestrate = new FrmUsu();
            Escritorio.add(muestrate);
            muestrate.show();
        } /*else if (DAT.MatrixNOEsNula() == false) {//si no hay perfiles configurados...
            JOptionPane.showMessageDialog(null, "Necesita Ingresar un perfil para carpetear", "Segundo lo segundo...", JOptionPane.ERROR_MESSAGE);
        } */ else {
            FrmCarpetear muestrate = new FrmCarpetear();
            Escritorio.add(muestrate);
            muestrate.show();
        }
    }//GEN-LAST:event_jMenuCarpetearActionPerformed

    private void jMenuPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPerfilesActionPerformed
        FrmPerfAdm muestrate = new FrmPerfAdm();
        Escritorio.add(muestrate);
        muestrate.show();
    }//GEN-LAST:event_jMenuPerfilesActionPerformed

    private void jMenuAcercadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcercadActionPerformed
        FrmAbout muestrate = new FrmAbout();
        Escritorio.add(muestrate);
        muestrate.show();
    }//GEN-LAST:event_jMenuAcercadActionPerformed

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
        //abre un sitio web
        Desktop enlace = Desktop.getDesktop();
        try {
            enlace.browse(new URI("https://armando8proyectos.blogspot.com/2023/03/proyecto-carpeteate.html"));
        } catch (IOException | URISyntaxException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuAcercad;
    private javax.swing.JMenuItem jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCarpetear;
    private javax.swing.JMenuItem jMenuEmail;
    private javax.swing.JMenuItem jMenuPerfiles;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
